#!/usr/bin/perl -w
#
# This file has been generated by mib2c using the mib2c.elasticsearch.conf
# file.
#
# Created on Mon Apr  7 14:35:19 2014

# The base OID for zalEs
our $base = '1.3.6.1.4.1.43278.10.10';

# Hash of all OIDs
our %oidmap = (
  #
  # Table objects
  zalEsIndicesEntry => {
    name => 'zalEsIndicesIndex',
    oid => '.1.3.6.1.4.1.43278.10.10.3.1.1.1',
    jref => '$cluster_health->{indices}',
    parent => 'zalEsIndicesTable',
    index => '1',
  },
  zalEsIndStatus => {
    type => ASN_INTEGER,
    jref => '{status}',
    oid => '.1.3.6.1.4.1.43278.10.10.3.1.1.2',
    parent => 'zalEsIndicesEntry',
    table_entry => 1,
  },
  zalEsIndName => {
    type => ASN_OCTET_STR,
    jref => '{name}',
    oid => '.1.3.6.1.4.1.43278.10.10.3.1.1.3',
    parent => 'zalEsIndicesEntry',
    table_entry => 1,
  },
  #
  # Scalars
  zalEsStatus => {
    type => ASN_INTEGER,
    jref => '$cluster_health->{status}',
    oid => '.1.3.6.1.4.1.43278.10.10.1.1',
  },
  zalEsClusterName => {
    type => ASN_OCTET_STR,
    jref => '$cluster_health->{cluster_name}',
    oid => '.1.3.6.1.4.1.43278.10.10.1.2',
  },
  zalEsNrNodes => {
    type => ASN_INTEGER,
    jref => '$cluster_health->{number_of_nodes}',
    oid => '.1.3.6.1.4.1.43278.10.10.1.3',
  },
  zalEsNrDataNodes => {
    type => ASN_INTEGER,
    jref => '$cluster_health->{number_of_data_nodes}',
    oid => '.1.3.6.1.4.1.43278.10.10.1.4',
  },
  zalEsDocsCount => {
    type => ASN_COUNTER64,
    jref => '$cluster_stats->{indices}->{docs}->{count}',
    oid => '.1.3.6.1.4.1.43278.10.10.1.5',
  },
  zalEsDocsDel => {
    type => ASN_COUNTER64,
    jref => '$cluster_stats->{indices}->{docs}->{deleted}',
    oid => '.1.3.6.1.4.1.43278.10.10.1.6',
  },
  zalEsStoreSize => {
    type => ASN_COUNTER64,
    jref => '$cluster_stats->{indices}->{store}->{size_in_bytes}',
    oid => '.1.3.6.1.4.1.43278.10.10.1.7',
  },
  zalEsStoreThr => {
    type => ASN_GAUGE,
    jref => '$cluster_stats->{indices}->{store}->{throttle_time_in_millis}',
    oid => '.1.3.6.1.4.1.43278.10.10.1.8',
  },
  zalEsMaster => {
    type => ASN_INTEGER,
    jref => '$cluster_state->{master_node}',
    oid => '.1.3.6.1.4.1.43278.10.10.1.9',
  },
  zalEsNodeName => {
    type => ASN_OCTET_STR,
    jref => '$node_stats->{name}',
    oid => '.1.3.6.1.4.1.43278.10.10.2.1',
  },
  zalEsIndexTotal => {
    type => ASN_COUNTER64,
    jref => '$node_stats->{indices}->{indexing}->{index_total}',
    oid => '.1.3.6.1.4.1.43278.10.10.2.2',
  },
  zalEsIndexTime => {
    type => ASN_COUNTER64,
    jref => '$node_stats->{indices}->{indexing}->{index_time_in_millis}',
    oid => '.1.3.6.1.4.1.43278.10.10.2.3',
  },
  zalEsFlushTotal => {
    type => ASN_COUNTER64,
    jref => '$node_stats->{indices}->{flush}->{total}',
    oid => '.1.3.6.1.4.1.43278.10.10.2.4',
  },
  zalEsFlushTime => {
    type => ASN_COUNTER64,
    jref => '$node_stats->{indices}->{flush}->{total_time_in_millis}',
    oid => '.1.3.6.1.4.1.43278.10.10.2.5',
  },
  zalEsThrottleTime => {
    type => ASN_COUNTER64,
    jref => '$node_stats->{indices}->{store}->{throttle_time_in_millis}',
    oid => '.1.3.6.1.4.1.43278.10.10.2.6',
  },
  zalEsDeleteTotal => {
    type => ASN_COUNTER64,
    jref => '$node_stats->{indices}->{indexing}->{delete_total}',
    oid => '.1.3.6.1.4.1.43278.10.10.2.7',
  },
  zalEsDeleteTime => {
    type => ASN_COUNTER64,
    jref => '$node_stats->{indices}->{indexing}->{delete_time_in_millis}',
    oid => '.1.3.6.1.4.1.43278.10.10.2.8',
  },
  zalEsGetTotal => {
    type => ASN_COUNTER64,
    jref => '$node_stats->{indices}->{get}->{total}',
    oid => '.1.3.6.1.4.1.43278.10.10.2.9',
  },
  zalEsGetTime => {
    type => ASN_COUNTER64,
    jref => '$node_stats->{indices}->{get}->{time_in_millis}',
    oid => '.1.3.6.1.4.1.43278.10.10.2.10',
  },
  zalEsExistsTotal => {
    type => ASN_COUNTER64,
    jref => '$node_stats->{indices}->{get}->{exists_total}',
    oid => '.1.3.6.1.4.1.43278.10.10.2.11',
  },
  zalEsExistsTime => {
    type => ASN_COUNTER64,
    jref => '$node_stats->{indices}->{get}->{exists_time_in_millis}',
    oid => '.1.3.6.1.4.1.43278.10.10.2.12',
  },
  zalEsMissingTotal => {
    type => ASN_COUNTER64,
    jref => '$node_stats->{indices}->{get}->{missing_total}',
    oid => '.1.3.6.1.4.1.43278.10.10.2.13',
  },
  zalEsMissingTime => {
    type => ASN_COUNTER64,
    jref => '$node_stats->{indices}->{get}->{missing_time_in_millis}',
    oid => '.1.3.6.1.4.1.43278.10.10.2.14',
  },
  zalEsQueryTotal => {
    type => ASN_COUNTER64,
    jref => '$node_stats->{indices}->{search}->{query_total}',
    oid => '.1.3.6.1.4.1.43278.10.10.2.15',
  },
  zalEsQueryTime => {
    type => ASN_COUNTER64,
    jref => '$node_stats->{indices}->{search}->{query_time_in_millis}',
    oid => '.1.3.6.1.4.1.43278.10.10.2.16',
  },
  zalEsFetchTotal => {
    type => ASN_COUNTER64,
    jref => '$node_stats->{indices}->{search}->{fetch_total}',
    oid => '.1.3.6.1.4.1.43278.10.10.2.17',
  },
  zalEsFetchTime => {
    type => ASN_COUNTER64,
    jref => '$node_stats->{indices}->{search}->{fetch_time_in_millis}',
    oid => '.1.3.6.1.4.1.43278.10.10.2.18',
  },
  zalEsMergeTotal => {
    type => ASN_COUNTER64,
    jref => '$node_stats->{indices}->{merges}->{total}',
    oid => '.1.3.6.1.4.1.43278.10.10.2.19',
  },
  zalEsMergeTime => {
    type => ASN_COUNTER64,
    jref => '$node_stats->{indices}->{merges}->{total_time_in_millis}',
    oid => '.1.3.6.1.4.1.43278.10.10.2.20',
  },
  zalEsRefreshTotal => {
    type => ASN_COUNTER64,
    jref => '$node_stats->{indices}->{refresh}->{total}',
    oid => '.1.3.6.1.4.1.43278.10.10.2.21',
  },
  zalEsRefreshTime => {
    type => ASN_COUNTER64,
    jref => '$node_stats->{indices}->{refresh}->{total_time_in_millis}',
    oid => '.1.3.6.1.4.1.43278.10.10.2.22',
  },
  zalEsProcMemResDel => {
    type => ASN_GAUGE,
    jref => '$node_stats->{process}->{mem}->{resident_in_bytes}',
    oid => '.1.3.6.1.4.1.43278.10.10.2.23',
  },
  zalEsProcMemShrDel => {
    type => ASN_GAUGE,
    jref => '$node_stats->{process}->{mem}->{share_in_bytes}',
    oid => '.1.3.6.1.4.1.43278.10.10.2.24',
  },
  zalEsProcCpuSysDel => {
    type => ASN_GAUGE,
    jref => '$node_stats->{process}->{cpu}->{sys_in_millis}',
    oid => '.1.3.6.1.4.1.43278.10.10.2.25',
  },
  zalEsProcCpuUsrDel => {
    type => ASN_GAUGE,
    jref => '$node_stats->{process}->{cpu}->{user_in_millis}',
    oid => '.1.3.6.1.4.1.43278.10.10.2.26',
  },
  zalEsTrspRxDel => {
    type => ASN_GAUGE,
    jref => '$node_stats->{transport}->{rx_count}',
    oid => '.1.3.6.1.4.1.43278.10.10.2.27',
  },
  zalEsTrspTxDel => {
    type => ASN_GAUGE,
    jref => '$node_stats->{transport}->{tx_count}',
    oid => '.1.3.6.1.4.1.43278.10.10.2.28',
  },
  zalEsTrspRxSzDel => {
    type => ASN_GAUGE,
    jref => '$node_stats->{transport}->{rx_size_in_bytes}',
    oid => '.1.3.6.1.4.1.43278.10.10.2.29',
  },
  zalEsTrspTxSzDel => {
    type => ASN_GAUGE,
    jref => '$node_stats->{transport}->{tx_size_in_bytes}',
    oid => '.1.3.6.1.4.1.43278.10.10.2.30',
  },
  zalEsSrchQrDel => {
    type => ASN_GAUGE,
    jref => '$node_stats->{indices}->{search}->{query_total}',
    oid => '.1.3.6.1.4.1.43278.10.10.2.31',
  },
  zalEsSrchFtDel => {
    type => ASN_GAUGE,
    jref => '$node_stats->{indices}->{search}->{fetch_total}',
    oid => '.1.3.6.1.4.1.43278.10.10.2.32',
  },
  zalEsSrchQrTmDel => {
    type => ASN_GAUGE,
    jref => '$node_stats->{indices}->{search}->{query_time_in_millis}',
    oid => '.1.3.6.1.4.1.43278.10.10.2.33',
  },
  zalEsSrchFtTmDel => {
    type => ASN_GAUGE,
    jref => '$node_stats->{indices}->{search}->{fetch_time_in_millis}',
    oid => '.1.3.6.1.4.1.43278.10.10.2.34',
  },
  zalEsGetDel => {
    type => ASN_GAUGE,
    jref => '$node_stats->{indices}->{get}->{total}',
    oid => '.1.3.6.1.4.1.43278.10.10.2.35',
  },
  zalEsGetExDel => {
    type => ASN_GAUGE,
    jref => '$node_stats->{indices}->{get}->{exists_total}',
    oid => '.1.3.6.1.4.1.43278.10.10.2.36',
  },
  zalEsGetMisDel => {
    type => ASN_GAUGE,
    jref => '$node_stats->{indices}->{get}->{missing_total}',
    oid => '.1.3.6.1.4.1.43278.10.10.2.37',
  },
  zalEsGetTmDel => {
    type => ASN_GAUGE,
    jref => '$node_stats->{indices}->{get}->{time_in_millis}',
    oid => '.1.3.6.1.4.1.43278.10.10.2.38',
  },
  zalEsGetExTmDel => {
    type => ASN_GAUGE,
    jref => '$node_stats->{indices}->{get}->{exists_time_in_millis}',
    oid => '.1.3.6.1.4.1.43278.10.10.2.39',
  },
  zalEsGetMisTmDel => {
    type => ASN_GAUGE,
    jref => '$node_stats->{indices}->{get}->{missing_time_in_millis}',
    oid => '.1.3.6.1.4.1.43278.10.10.2.40',
  },
);

1;
