#!/usr/bin/perl -w
#
#
# WARNING: DO NOT EDIT THIS FILE BY HAND.
#
# This file has been generated by mib2c using the mib2c.perl.conf file
# This is intended to be used by the net-snmp agent with embedded perl
# support. See perldoc NetSNMP::agent
#
# Created on Wed Mar 19 19:58:00 2014
#
# To load this into a running agent with embedded perl support turned
# on, simply put the following line (without the leading # mark) your
# snmpd.conf file:
#
# perl do 'path/to/agent_1.3.6.1.4.1.43278.10.10.pl'
#
# You will need a copy of NetSNMP installed. This has been developed using
# NetSNMP version 5.2.2
#



use NetSNMP::agent::Support;
use NetSNMP::ASN (':all');

# Include the functions to handle the nodes
do 'functions.pl';


# Hash for all OIDs
my  $oidtable={
# Table objects
    ".1.3.6.1.4.1.43278.10.10.2.1.1.2"=>{func=>\&get_zalEsClusterName,type=>ASN_OCTET_STR, check=>\&check_zalEsStateTable, nextoid=>\&next_zalEsStateTable, istable=>'1', next=>"", numindex=>1},
    ".1.3.6.1.4.1.43278.10.10.2.1.1.3"=>{func=>\&get_zalEsMaster,type=>ASN_OCTET_STR, check=>\&check_zalEsStateTable, nextoid=>\&next_zalEsStateTable, istable=>'1', next=>"", numindex=>1},
    ".1.3.6.1.4.1.43278.10.10.2.1.1.4"=>{func=>\&get_zalEsStatus,type=>ASN_INTEGER, check=>\&check_zalEsStateTable, nextoid=>\&next_zalEsStateTable, istable=>'1', next=>"", numindex=>1},
    ".1.3.6.1.4.1.43278.10.10.2.1.1.5"=>{func=>\&get_zalEsNrNodes,type=>ASN_INTEGER, check=>\&check_zalEsStateTable, nextoid=>\&next_zalEsStateTable, istable=>'1', next=>"", numindex=>1},
    ".1.3.6.1.4.1.43278.10.10.2.1.1.6"=>{func=>\&get_zalEsShardsActive,type=>ASN_INTEGER, check=>\&check_zalEsStateTable, nextoid=>\&next_zalEsStateTable, istable=>'1', next=>"", numindex=>1},
    ".1.3.6.1.4.1.43278.10.10.2.1.1.7"=>{func=>\&get_zalEsShardsReloc,type=>ASN_INTEGER, check=>\&check_zalEsStateTable, nextoid=>\&next_zalEsStateTable, istable=>'1', next=>"", numindex=>1},
    ".1.3.6.1.4.1.43278.10.10.2.1.1.8"=>{func=>\&get_zalEsShardsInit,type=>ASN_INTEGER, check=>\&check_zalEsStateTable, nextoid=>\&next_zalEsStateTable, istable=>'1', next=>"", numindex=>1},
    ".1.3.6.1.4.1.43278.10.10.2.1.1.9"=>{func=>\&get_zalEsShardsUnas,type=>ASN_INTEGER, check=>\&check_zalEsStateTable, nextoid=>\&next_zalEsStateTable, istable=>'1', next=>"", numindex=>1},
    ".1.3.6.1.4.1.43278.10.10.2.1.1.10"=>{func=>\&get_zalEsShardsPrim,type=>ASN_INTEGER, check=>\&check_zalEsStateTable, nextoid=>\&next_zalEsStateTable, istable=>'1', next=>"", numindex=>1},
    ".1.3.6.1.4.1.43278.10.10.3.1.1.2"=>{func=>\&get_zalEsNodeName,type=>ASN_OCTET_STR, check=>\&check_zalEsNodeTable, nextoid=>\&next_zalEsNodeTable, istable=>'1', next=>"", numindex=>1},
    ".1.3.6.1.4.1.43278.10.10.3.1.1.3"=>{func=>\&get_zalEsStoreSize,type=>ASN_COUNTER64, check=>\&check_zalEsNodeTable, nextoid=>\&next_zalEsNodeTable, istable=>'1', next=>"", numindex=>1},
    ".1.3.6.1.4.1.43278.10.10.3.1.1.4"=>{func=>\&get_zalEsDocs,type=>ASN_COUNTER64, check=>\&check_zalEsNodeTable, nextoid=>\&next_zalEsNodeTable, istable=>'1', next=>"", numindex=>1},
    ".1.3.6.1.4.1.43278.10.10.3.1.1.5"=>{func=>\&get_zalEsIndexOps,type=>ASN_COUNTER64, check=>\&check_zalEsNodeTable, nextoid=>\&next_zalEsNodeTable, istable=>'1', next=>"", numindex=>1},
    ".1.3.6.1.4.1.43278.10.10.3.1.1.6"=>{func=>\&get_zalEsIndexTime,type=>ASN_GAUGE, check=>\&check_zalEsNodeTable, nextoid=>\&next_zalEsNodeTable, istable=>'1', next=>"", numindex=>1},
    ".1.3.6.1.4.1.43278.10.10.3.1.1.7"=>{func=>\&get_zalEsFlushOps,type=>ASN_COUNTER64, check=>\&check_zalEsNodeTable, nextoid=>\&next_zalEsNodeTable, istable=>'1', next=>"", numindex=>1},
    ".1.3.6.1.4.1.43278.10.10.3.1.1.8"=>{func=>\&get_zalEsFlushTime,type=>ASN_GAUGE, check=>\&check_zalEsNodeTable, nextoid=>\&next_zalEsNodeTable, istable=>'1', next=>"", numindex=>1},
    ".1.3.6.1.4.1.43278.10.10.3.1.1.9"=>{func=>\&get_zalEsThrottleTime,type=>ASN_GAUGE, check=>\&check_zalEsNodeTable, nextoid=>\&next_zalEsNodeTable, istable=>'1', next=>"", numindex=>1},
    ".1.3.6.1.4.1.43278.10.10.3.1.1.10"=>{func=>\&get_zalEsDeleteOps,type=>ASN_COUNTER64, check=>\&check_zalEsNodeTable, nextoid=>\&next_zalEsNodeTable, istable=>'1', next=>"", numindex=>1},
    ".1.3.6.1.4.1.43278.10.10.3.1.1.11"=>{func=>\&get_zalEsDeleteTime,type=>ASN_GAUGE, check=>\&check_zalEsNodeTable, nextoid=>\&next_zalEsNodeTable, istable=>'1', next=>"", numindex=>1},
    ".1.3.6.1.4.1.43278.10.10.3.1.1.12"=>{func=>\&get_zalEsGetOps,type=>ASN_COUNTER64, check=>\&check_zalEsNodeTable, nextoid=>\&next_zalEsNodeTable, istable=>'1', next=>"", numindex=>1},
    ".1.3.6.1.4.1.43278.10.10.3.1.1.13"=>{func=>\&get_zalEsGetTime,type=>ASN_GAUGE, check=>\&check_zalEsNodeTable, nextoid=>\&next_zalEsNodeTable, istable=>'1', next=>"", numindex=>1},
    ".1.3.6.1.4.1.43278.10.10.3.1.1.14"=>{func=>\&get_zalEsExistsOps,type=>ASN_COUNTER64, check=>\&check_zalEsNodeTable, nextoid=>\&next_zalEsNodeTable, istable=>'1', next=>"", numindex=>1},
    ".1.3.6.1.4.1.43278.10.10.3.1.1.15"=>{func=>\&get_zalEsExistsTime,type=>ASN_GAUGE, check=>\&check_zalEsNodeTable, nextoid=>\&next_zalEsNodeTable, istable=>'1', next=>"", numindex=>1},
    ".1.3.6.1.4.1.43278.10.10.3.1.1.16"=>{func=>\&get_zalEsMissingOps,type=>ASN_COUNTER64, check=>\&check_zalEsNodeTable, nextoid=>\&next_zalEsNodeTable, istable=>'1', next=>"", numindex=>1},
    ".1.3.6.1.4.1.43278.10.10.3.1.1.17"=>{func=>\&get_zalEsMissingTime,type=>ASN_GAUGE, check=>\&check_zalEsNodeTable, nextoid=>\&next_zalEsNodeTable, istable=>'1', next=>"", numindex=>1},
    ".1.3.6.1.4.1.43278.10.10.3.1.1.18"=>{func=>\&get_zalEsQueryOps,type=>ASN_COUNTER64, check=>\&check_zalEsNodeTable, nextoid=>\&next_zalEsNodeTable, istable=>'1', next=>"", numindex=>1},
    ".1.3.6.1.4.1.43278.10.10.3.1.1.19"=>{func=>\&get_zalEsQueryTime,type=>ASN_GAUGE, check=>\&check_zalEsNodeTable, nextoid=>\&next_zalEsNodeTable, istable=>'1', next=>"", numindex=>1},
    ".1.3.6.1.4.1.43278.10.10.3.1.1.20"=>{func=>\&get_zalEsFetchOps,type=>ASN_COUNTER64, check=>\&check_zalEsNodeTable, nextoid=>\&next_zalEsNodeTable, istable=>'1', next=>"", numindex=>1},
    ".1.3.6.1.4.1.43278.10.10.3.1.1.21"=>{func=>\&get_zalEsFetchTime,type=>ASN_GAUGE, check=>\&check_zalEsNodeTable, nextoid=>\&next_zalEsNodeTable, istable=>'1', next=>"", numindex=>1},
    ".1.3.6.1.4.1.43278.10.10.3.1.1.22"=>{func=>\&get_zalEsMergeOps,type=>ASN_COUNTER64, check=>\&check_zalEsNodeTable, nextoid=>\&next_zalEsNodeTable, istable=>'1', next=>"", numindex=>1},
    ".1.3.6.1.4.1.43278.10.10.3.1.1.23"=>{func=>\&get_zalEsMergeTime,type=>ASN_GAUGE, check=>\&check_zalEsNodeTable, nextoid=>\&next_zalEsNodeTable, istable=>'1', next=>"", numindex=>1},
    ".1.3.6.1.4.1.43278.10.10.3.1.1.24"=>{func=>\&get_zalEsRefreshOps,type=>ASN_COUNTER64, check=>\&check_zalEsNodeTable, nextoid=>\&next_zalEsNodeTable, istable=>'1', next=>"", numindex=>1},
    ".1.3.6.1.4.1.43278.10.10.3.1.1.25"=>{func=>\&get_zalEsRefreshTime,type=>ASN_GAUGE, check=>\&check_zalEsNodeTable, nextoid=>\&next_zalEsNodeTable, istable=>'1', next=>"", numindex=>1},
# Scalars
};

# Register the top oid with the agent
registerAgent($agent, '1.3.6.1.4.1.43278.10.10', $oidtable);

